name: Deploy to App Engine

on: workflow_dispatch
jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticating"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        env:
          CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800 # 30 minutes

      # Example of using the output
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.version_url }}"'
