name: Deploy to App Engine

on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v2
        with:
          project: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: ./app.yaml
          credentials: ${{ secrets.GCP_CREDENTIALS }}
